urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2011-2015 Slack
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from django.conf.urls import include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^contact/', include('contact.urls')),

    url(r'^admin/', admin.site.urls),
    
    url(r'^', include('descgen.urls'))
 ]

descgen/models.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2011-2015 Slack
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator
from django.db.models.signals import m2m_changed, post_delete, post_save, pre_delete
from django.db.models.query import Q
from django.db.models import Max

from .scraper.factory import SCRAPER_CHOICES


class PublicTemplateManager(models.Manager):

    def get_queryset(self):
        return super(PublicTemplateManager, self).get_queryset().filter(Q(is_default__exact=True) | Q(is_public__exact=True))


class Template(models.Model):

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=40,
                            help_text='Enter the name of the template here.')
    template = models.TextField(validators=[MaxLengthValidator(8192)], blank=True, help_text='Enter the template code here.')
    is_public = models.BooleanField(default=False,
                                    help_text='Make this template public. Public templates can be used by all users that are subscribed to you.')
    is_default = models.BooleanField(default=False,
                                     help_text='Make this template a default. Default templates can be used by all registered users and users that are not logged in.')
    is_utility = models.BooleanField(default=False,
                                     help_text="Mark this template as a utility. Utility templates are only used as the basis for other templates and won't appear in the list of available templates for rendering a release directly.")
    dependencies = models.ManyToManyField('self', symmetrical=False, related_name='depending_set', blank=True,
                                          help_text='Choose which templates this template depends on. Chosen templates can be included or extended in your template code.')

    objects = models.Manager()
    public_templates = PublicTemplateManager()

    def __unicode__(self):
        out = self.name
        if not self.is_default:
            out += u' [%s]' % self.owner.username
        return out

    def visible_to_user(self, user, assume_subscription=False):
        if user is None:
            return self.is_default
        else:
            if assume_subscription:
                return self.is_default or self.owner_id == user.id or self.is_public
            else:
                return self.is_default or self.owner_id == user.id or (self.owner.subscriber_set.filter(subscriber__exact=user).exists() and self.is_public)

    @property
    def is_visible(self):
        return self.is_default or self.is_public

    def get_unique_name(self):
        return 'template_%d' % self.pk

    def depends_on(self):
        return u', '.join(map(unicode, self.dependencies.all()))

    def dependencies_set(self):
        res = set()
        for f in self.dependencies.all():
            res.add(f)
            res.update(f.dependencies_set())
        return res

    def cached_dependencies_set(self, prefetch_owner=False):
        res = set()
        l = DependencyClosure.objects.filter(descendant__exact=self, path_length__gt=0).values('ancestor_id').distinct()
        q = Template.objects.filter(id__in=l)
        if prefetch_owner:
            q = q.select_related('owner')
        for f in q:
            res.add(f)
        return res

    def max_dependency_height(self, include_descendants):
        aggregate = DependencyClosure.objects.filter(descendant__exact=self).aggregate(max_height=Max('path_length'))
        height = aggregate['max_height']
        if include_descendants:
            aggregate = DependencyClosure.objects.filter(ancestor__exact=self).aggregate(max_height=Max('path_length'))
            height += aggregate['max_height']
        return height

    def depending_templates_requiring_public(self):
        return self.depending_set.filter(~Q(owner_id__exact=self.owner_id) | Q(owner_id__exact=self.owner_id, is_public__exact=True))

    @staticmethod
    def circular_checker(parent, child):
        """
        Checks that the object is not an ancestor or a descendant,
        avoid self links
        """
        if parent == child:
            raise ValidationError('A template may not depend on itself.')
        # child is only hashable if the primary key is set; child has to be hashable in order to check whether
        # it is part of the dependency set, so only check for this if pk is set
        # an empty pk means that child is not yet saved in the database and therefore cannot be a dependency for parent
        if child.pk and child in parent.dependencies_set():
            raise ValidationError('One of the dependencies has a dependency on this template.')

    @staticmethod
    def templates_for_user(user, with_utility=True, sort_by_name=False, prefetch_owner=False):
        if user is not None and user.is_authenticated:
            subscribed_to = user.subscribed_to.values('user_id').distinct()
            t = Template.objects.filter(Q(owner__in=subscribed_to, is_public__exact=True) | Q(owner__exact=user.pk) | Q(is_default__exact=True))
        else:
            t = Template.objects.filter(is_default__exact=True)
        if not with_utility:
            t = t.filter(is_utility__exact=False)
        if prefetch_owner:
            t = t.select_related('owner')
        if sort_by_name:
            t = t.extra(select={'lower_name': 'lower(name)'}).order_by('lower_name')
        return t

    class Meta:
        unique_together = ('owner', 'name')


class DependencyClosure(models.Model):

    descendant = models.ForeignKey(Template, related_name='closure_descendant', on_delete=models.CASCADE)
    ancestor = models.ForeignKey(Template, related_name='closure_ancestor', on_delete=models.CASCADE)
    path_length = models.IntegerField()
    count = models.IntegerField()

    class Meta:
        unique_together = ('descendant', 'ancestor', 'path_length')

    def __unicode__(self):
        return u'%s depends on %s over %d hops' % (self.descendant, self.ancestor, self.path_length)


def dependency_changed(sender, **kwargs):
    """
    This method for updating the dependency closures assumes that only the forward relation for the many-to-many field
    is ever modified, i.e. template.dependencies.add(other_template) and never other_template.depending_set.add(template)
    """
    action = kwargs['action']
    if action == 'post_add':
        instance = kwargs['instance']
        pk_set = kwargs['pk_set']
        # get all templates that depend on the we one that was modified and are at least one hop away (exclude the self
        # links)
        modified_instance_descendants = DependencyClosure.objects.filter(ancestor_id__exact=instance.pk, path_length__gt=0)
        for pk in pk_set:
            # for every added dependency and it's dependencies we add a new path from the modified instance
            current_pk_ancestors = DependencyClosure.objects.filter(descendant_id__exact=pk)
            for current_pk_ancestor in current_pk_ancestors:
                # old situation:   pk --> ... --> current_pk_ancestor
                #                     \         /
                #                     path_length
                #
                # new situation:   instance --> pk --> ... --> current_pk_ancestor
                #                           \               /
                #                            path_length + 1
                #
                # Note: every template automatically has the path:         pk --
                #                                                           ^   \  length = 0
                #                                                            \__/
                #       so the path    instance --> pk   with length 1
                #       will be added without the need for any special corner case handling
                try:
                    # see if we already have a path from instance to current_pk_ancestor with the expected length
                    path_to_ancestor = DependencyClosure.objects.get(descendant_id__exact=instance.pk, ancestor_id__exact=current_pk_ancestor.ancestor_id, path_length=current_pk_ancestor.path_length+1)
                except DependencyClosure.DoesNotExist:
                    # if we don't create one
                    path_to_ancestor = DependencyClosure.objects.create(descendant_id=instance.pk, ancestor_id=current_pk_ancestor.ancestor_id, path_length=current_pk_ancestor.path_length+1, count=current_pk_ancestor.count)
                else:
                    # otherwise increase the count to include the new paths
                    path_to_ancestor.count += current_pk_ancestor.count
                    path_to_ancestor.save()

templates/user/subscribe_form.html
<form action="{% url 'subscribe_to_user' %}?next={{ request.path }}{% if get_query_string %}%3F{{ get_query_string }}{% endif %}" method="post" id="subscribe_form_{{ sub_user.pk }}">
    {% csrf_token %}
    {{ subscribe_form }}
    <button type="submit" class="btn btn-success" id="subscribe_submit_{{ sub_user.pk }}" title="Subscribing to a user grants access to all of their public templates.">Subscribe</button>
</form>

templates/user/subscriptions.html
{% extends "base.html" %}

{% block title %}My subscriptions – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block subscriptions_li_tags %} active{% endblock %}

{% if is_paginated %}{% load paginator %}{% endif %}

{% block content %}
    <h2 class="mb-4">My subscriptions</h2>

    {% if is_paginated %}<div class="mb-4">{% paginator 2 %}</div>{% endif %}
    {% if subscriptions %}
        <div class="table-responsive mb-4">
            <table class="table table-striped table-bordered m-0">
                <thead>
                <tr>
                    <th>User</th>
                    <th style="width: 1rem;"></th>
                </tr>
                </thead>
                <tbody>
                {% for user_obj in subscriptions %}
                    <tr>
                        <td class="align-middle"><a
                                href="{% url 'user_detail' user_obj.pk %}">{{ user_obj.username }}</a></td>
                        <td>{% include 'user/unsubscribe_button.html' with unsub_user=user_obj %}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="alert alert-info mb-4">You are not subscribed to any users.</div>
    {% endif %}
    {% if is_paginated %}<div class="mb-4">{% paginator 2 %}</div>{% endif %}
{% endblock %}

templates/user/unsubscribe.html
{% extends "base.html" %}

{% block title %}Sure? – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block content %}
    {% if form.errors %}
        <h2 class="mb-4">What did you do?</h2>
        <div class="alert alert-danger mb-4">{{ form.user_id.errors }}</div>
    {% else %}
        {% if dependant_templates %}
            <div class="alert alert-warning mb-4">
                <ul class="m-0 list-unstyled">
                    <li>
                        The following templates will be affected:
                        <ul class="m-0">
                            {% for template in dependant_templates %}
                                <li><a href="{% url 'template_edit' template.id %}">{{ template.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </div>
        {% endif %}

        <div class="card mb-4">
            <h5 class="card-header">Are you sure?</h5>

            <div class="card-body">
                <p class="m-0">
                    Are you sure you want to unsubscribe from <strong>{{ unsub_user.username }}</strong>?
                    If you click yes all of your templates that have a dependency to one of
                    <strong>{{ unsub_user.username }}</strong>'s templates won't be functional anymore.
                </p>

                <form action="{% url 'unsubscribe' %}" method="post" id="unsubscribe_form">
                    {% csrf_token %}
                    {{ form }}
                    <button type="submit" class="btn btn-danger mt-3">Yes, I'm sure</button>
                </form>
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/user/unsubscribe_button.html
<a href="{% url 'unsubscribe' %}?user_id={{ unsub_user.pk }}&amp;next={{ request.path }}{% if get_query_string %}%3F{{ get_query_string }}{% endif %}" id="unsubscribe_{{ unsub_user.pk }}" class="btn btn-danger">Unsubscribe</a>

templates/user/user_detail.html
{% extends "base.html" %}

{% block title %}User: {{ user_obj.username }} – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block userpage_li_tags %}{% if user == user_obj %} active{% endif %}{% endblock %}

{% load subscribedto %}
{% load templatevisible %}
{% load addforms %}

{% block content %}
    {% with is_subscribed_to=request.user|subscribedto:user_obj %}
        <div class="row">
            <h2 class="col-12 col-md-auto mb-4 text-truncate">
                {{ user_obj.username }}{% if user == user_obj %}
                    <small class="text-muted">(You)</small>{% endif %}
            </h2>
            {% if user.pk != user_obj.pk %}
                <div class="col-12 col-md-auto ml-auto mb-4">
                    {% if not is_subscribed_to %}
                        {% with subscribe_form=user_obj|subscribe_form %}
                            {% include 'user/subscribe_form.html' with sub_user=user_obj %}
                        {% endwith %}
                    {% else %}
                        {% include 'user/unsubscribe_button.html' with unsub_user=user_obj %}
                    {% endif %}
                </div>
            {% endif %}
        </div>


        <h3>General information</h3>
        <dl class="mb-4">
            <dt>Number of subscribers:</dt>
            <dd>{{ num_subscribers }}</dd>

            <dt>Number of templates:</dt>
            <dd>{{ num_templates }}</dd>

            <dt>Number of public templates:</dt>
            <dd>{{ num_public_templates }}{% if num_templates > 0 %} ({{ public_percent }}%){% endif %}</dd>

            {% if user == user_obj %}
                <dt>API token:</dt>
                {% if token %}
                    <dd>
                        <span class="d-inline-block text-truncate mw-100 align-middle">{{ token }}</span>
                        <span class="d-inline-block align-middle">(<a href="{% url 'api_token' %}">Create new API token</a>)</span>
                    </dd>
                {% else %}
                    <dd><a href="{% url 'api_token' %}">Create API token</a></dd>
                {% endif %}
            {% endif %}
        </dl>

        <h3>Templates</h3>
        {% with templates=user_obj.template_set.all|getvisiblefor:user|dictsort:"name.lower" %}
            {% if templates %}
                <div class="mb-4 table-responsive">{% include 'template/template_overview_table.html' %}</div>
            {% else %}
                <div class="alert alert-secondary mb-4">This user does not have any public templates.</div>
            {% endif %}
        {% endwith %}
    {% endwith %}
{% endblock %}

templates/user/user_does_not_exist.html
{% extends "base.html" %}

{% block title %}Error – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block content %}
    <div class="alert alert-danger mb-4">The requested user does not exist.</div>
{% endblock %}

templates/user/user_list.html
{% extends "base.html" %}

{% block title %}Users – {% endblock %}

{% block home_li_tags %}{% endblock %}

{% block userlist_li_tags %} active{% endblock %}

{% if is_paginated %}{% load paginator %}{% endif %}
{% load addforms %}
{% load subscribedto %}
{% load templatevisible %}

{% block content %}
    <h2 class="mb-4">Users</h2>

    <div class="row">
        <div class="col-12 col-md-auto ml-auto mb-4">{% include 'user/user_search_form.html' %}</div>
    </div>

    {% if is_paginated %}
        <div class="mb-4">{% paginator 2 %}</div>
    {% endif %}
    <ul class="list-unstyled">
        {% with get_query_string=request.GET.urlencode|urlencode %}
            {% for user_obj in users %}
                {% with is_subscribed_to=request.user|subscribedto:user_obj %}
                    <li class="card bg-light mb-4 p-3">
                        <div class="row">
                            <div class="col-12 col-md-auto mb-3">
                                <h3 class="m-0"><a
                                        href="{% url 'user_detail' user_obj.pk %}">{{ user_obj.username }}</a></h3>
                            </div>
                            <div class="col-12 ml-auto col-md-auto mb-3">
                                {% if request.user.pk != user_obj.pk %}
                                    {% if not is_subscribed_to %}
                                        {% with subscribe_form=user_obj|subscribe_form %}
                                            {% include 'user/subscribe_form.html' with sub_user=user_obj %}
                                        {% endwith %}
                                    {% else %}
                                        {% include 'user/unsubscribe_button.html' with unsub_user=user_obj %}
                                    {% endif %}
                                {% endif %}

                            </div>
                        </div>

                        {% with all_templates=user_obj.template_set.all|getvisiblefor:request.user|dictsort:"name.lower" %}
                            {% if all_templates %}
                                {% include 'template/template_overview_table.html' with templates=all_templates|slice:":20" %}
                                {% if all_templates|length > 20 %}
                                    <p class="alert alert-info m-0 mt-3"><strong>Note:</strong> The list of public templates of this user has been
                                        truncated. To view the whole list visit the <a href="{% url 'user_detail' user_obj.pk %}">user page</a>.</p>
                                {% endif %}
                            {% else %}
                                <div class="alert alert-secondary m-0">This user does not have any public templates.</div>
                            {% endif %}
                        {% endwith %}
                    </li>
                {% endwith %}
            {% empty %}
                <li class="alert alert-info mb-4">No users to display.</li>
            {% endfor %}
        {% endwith %}
    </ul>
    {% if is_paginated %}
        <div class="mb-4">{% paginator 2 %}</div>
    {% endif %}
{% endblock %}

templates/user/user_search_form.html
{% load with_attrs %}<form action="{% url 'user_list' %}" method="get" id="user_search_form" class="form-row">
    <div class="col-12 col-md-auto mb-3 mb-md-0">
        <label class="sr-only" for="{{ user_search_form.username.id_for_label }}">{{ user_search_form.username.label }}</label>
        {{ user_search_form.username|with_attrs:"form-control" }}
    </div>

    <div class="col-12 col-md-auto mb-3 mb-md-0">
        <label class="sr-only" for="{{ user_search_form.template_name.id_for_label }}">{{ user_search_form.template_name.label }}</label>
        {{ user_search_form.template_name|with_attrs:"form-control" }}
    </div>

    <div class="col-auto">
        <button class="btn btn-secondary" type="submit">Search</button>
    </div>
</form>